name = "my-cf-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

# [site]
# bucket = "./public"

[[d1_databases]]
binding = "DB"
database_name = "anvsa"
database_id = "cb6a86cc-1008-4899-88a9-df1bc1c38403"
